### ISSUE TITLE
BlackJack Assignment Done

### ISSUE THREAD

**Issue by sbeleuz** [sbeleuz/ICS3U#4]
Here is the final version of my BlackJack assignment. Please let me know if you can access it or if there are any problems. 

https://github.com/sbeleuz/ICS3U/tree/master/Blackjack

**Comment by kevindeslauriers** [comment]
Excellent Work Sabina - the program is well written and very well organised through the use of methods.

You had comments throughout that will help you later on decipher what your code does.

I did notice that the amount that was bet was not reset and seemed to be cumulative.

K 9.5 / 10
I 15 / 15
C 10 / 10
A 10 / 10

98.8%
