### ISSUE TITLE
Horse-Racing Assignment (for marking)

### ISSUE THREAD

**Issue by sbeleuz** [sbeleuz/ICS3U#6]
Here is my finished project. 
https://github.com/sbeleuz/ICS3U/tree/master/HorseRacing/src

**Comment by kevindeslauriers** [comment]
Excellent Work Sabina! You have designed and implemented a very good Horse Racing game. It is extremely well organised and you have done an exceptional job with error handling.

Good Job using a 2D array!

K 10 / 10
I  15 / 15
C 10 / 10
A 10 / 10
